language: generic

services:
  - docker

templates:
  django111: &django111 DJANGO_VERSION="==1.11.*"
  django21: &django21 DJANGO_VERSION="==2.1.*"
  django22: &django22 DJANGO_VERSION="==2.2.*"
  py2: &py2 PYTHON_VERSION=2
  py3: &py3 PYTHON_VERSION=3

matrix:
  fast_finish: true
  include:
    - env: [*django111, *py2]
#    - env: [*django21, *py3]
#    - env: [*django23, *py3]


before_install:
  - export DOCKER_COMPOSE_VERSION=1.23.2
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - echo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose run -e TRAVIS -e TRAVIS_JOB_ID -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST web bash -c 'pip install coverage coveralls && coverage run --branch --omit=*/site-packages/*,poradnia/*/migrations/*.py manage.py test --keepdb --verbosity=2 && coveralls'
